// 300+ exercises organized by muscle group
const exercises = [
  // ============ CHEST ============
  { name: 'Barbell Bench Press', category: 'Barbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Barbell, Bench', instructions: 'Lie on a flat bench, grip the bar slightly wider than shoulder width. Lower to chest, press back up.' },
  { name: 'Incline Barbell Bench Press', category: 'Barbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Barbell, Incline Bench', instructions: 'Set bench to 30-45 degrees. Press barbell from upper chest.' },
  { name: 'Decline Barbell Bench Press', category: 'Barbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Barbell, Decline Bench', instructions: 'Lie on decline bench, press barbell from lower chest.' },
  { name: 'Close Grip Bench Press', category: 'Barbell', primaryMuscles: ['Chest', 'Triceps'], secondaryMuscles: ['Shoulders'], equipment: 'Barbell, Bench', instructions: 'Grip bar with hands shoulder width apart, press from chest.' },
  { name: 'Dumbbell Bench Press', category: 'Dumbbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Dumbbells, Bench', instructions: 'Lie on flat bench, press dumbbells up from chest level.' },
  { name: 'Incline Dumbbell Bench Press', category: 'Dumbbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Dumbbells, Incline Bench', instructions: 'Set bench to 30-45 degrees. Press dumbbells up.' },
  { name: 'Decline Dumbbell Bench Press', category: 'Dumbbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Dumbbells, Decline Bench', instructions: 'Lie on decline bench, press dumbbells.' },
  { name: 'Dumbbell Fly', category: 'Dumbbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: 'Dumbbells, Bench', instructions: 'Lie on bench, arms extended. Lower dumbbells in arc motion, squeeze chest to return.' },
  { name: 'Incline Dumbbell Fly', category: 'Dumbbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: 'Dumbbells, Incline Bench', instructions: 'Set bench to incline. Perform fly motion focusing on upper chest.' },
  { name: 'Cable Crossover', category: 'Cable', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: 'Cable Machine', instructions: 'Stand between cable towers, bring handles together in arc motion.' },
  { name: 'Low Cable Crossover', category: 'Cable', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: 'Cable Machine', instructions: 'Set cables low, bring handles up and together in arc motion.' },
  { name: 'Machine Chest Press', category: 'Machine', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Chest Press Machine', instructions: 'Sit in machine, press handles forward.' },
  { name: 'Pec Deck', category: 'Machine', primaryMuscles: ['Chest'], secondaryMuscles: [], equipment: 'Pec Deck Machine', instructions: 'Sit in machine, bring pads together by squeezing chest.' },
  { name: 'Push-Up', category: 'Bodyweight', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'None', instructions: 'Hands shoulder width apart, lower body to floor, push back up.' },
  { name: 'Diamond Push-Up', category: 'Bodyweight', primaryMuscles: ['Chest', 'Triceps'], secondaryMuscles: ['Shoulders'], equipment: 'None', instructions: 'Hands together forming diamond shape, perform push-up.' },
  { name: 'Dip (Chest)', category: 'Bodyweight', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Dip Bars', instructions: 'Lean forward on dip bars, lower body, press back up.' },
  { name: 'Landmine Press', category: 'Barbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders', 'Triceps'], equipment: 'Barbell, Landmine', instructions: 'Press barbell from chest height using landmine attachment.' },
  { name: 'Floor Press', category: 'Barbell', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps'], equipment: 'Barbell', instructions: 'Lie on floor, press barbell from chest. Limited ROM at bottom.' },
  { name: 'Svend Press', category: 'Other', primaryMuscles: ['Chest'], secondaryMuscles: [], equipment: 'Weight Plate', instructions: 'Squeeze plates together at chest level, extend arms forward.' },

  // ============ BACK ============
  { name: 'Barbell Row', category: 'Barbell', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps', 'Traps'], equipment: 'Barbell', instructions: 'Bend over, pull barbell to lower chest/upper abs.' },
  { name: 'Pendlay Row', category: 'Barbell', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps', 'Traps'], equipment: 'Barbell', instructions: 'Strict barbell row from floor each rep. Torso parallel.' },
  { name: 'T-Bar Row', category: 'Barbell', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps', 'Traps'], equipment: 'T-Bar', instructions: 'Straddle bar, row T-bar handle to chest.' },
  { name: 'Dumbbell Row', category: 'Dumbbell', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps'], equipment: 'Dumbbell, Bench', instructions: 'One arm at a time, pull dumbbell to hip while supported on bench.' },
  { name: 'Seated Cable Row', category: 'Cable', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps', 'Traps'], equipment: 'Cable Machine', instructions: 'Sit at cable row, pull handle to torso, squeeze shoulder blades.' },
  { name: 'Single Arm Cable Row', category: 'Cable', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps'], equipment: 'Cable Machine', instructions: 'Pull single cable handle to hip, one arm at a time.' },
  { name: 'Pull-Up', category: 'Bodyweight', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps'], equipment: 'Pull-Up Bar', instructions: 'Hang from bar, pull chin above bar.' },
  { name: 'Chin-Up', category: 'Bodyweight', primaryMuscles: ['Back', 'Lats', 'Biceps'], secondaryMuscles: [], equipment: 'Pull-Up Bar', instructions: 'Underhand grip, pull chin above bar.' },
  { name: 'Lat Pulldown', category: 'Cable', primaryMuscles: ['Lats', 'Back'], secondaryMuscles: ['Biceps'], equipment: 'Lat Pulldown Machine', instructions: 'Pull bar down to upper chest, squeeze lats.' },
  { name: 'Close Grip Lat Pulldown', category: 'Cable', primaryMuscles: ['Lats', 'Back'], secondaryMuscles: ['Biceps'], equipment: 'Lat Pulldown Machine', instructions: 'Use close grip handle, pull to chest.' },
  { name: 'Straight Arm Pulldown', category: 'Cable', primaryMuscles: ['Lats'], secondaryMuscles: ['Triceps'], equipment: 'Cable Machine', instructions: 'Keep arms straight, pull bar down to thighs.' },
  { name: 'Machine Row', category: 'Machine', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps'], equipment: 'Row Machine', instructions: 'Sit at machine, pull handles to torso.' },
  { name: 'Inverted Row', category: 'Bodyweight', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps'], equipment: 'Smith Machine or Barbell in Rack', instructions: 'Hang under bar, pull chest to bar.' },
  { name: 'Meadows Row', category: 'Barbell', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps'], equipment: 'Barbell, Landmine', instructions: 'Stand perpendicular to landmine, row with one arm.' },
  { name: 'Chest Supported Row', category: 'Dumbbell', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps', 'Traps'], equipment: 'Dumbbells, Incline Bench', instructions: 'Lie face down on incline bench, row dumbbells.' },
  { name: 'Kroc Row', category: 'Dumbbell', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps', 'Traps'], equipment: 'Heavy Dumbbell', instructions: 'High-rep heavy single arm dumbbell rows with some body English.' },
  { name: 'Seal Row', category: 'Barbell', primaryMuscles: ['Back'], secondaryMuscles: ['Biceps'], equipment: 'Barbell, Elevated Bench', instructions: 'Lie face down on elevated bench, row barbell.' },

  // ============ SHOULDERS ============
  { name: 'Overhead Press', category: 'Barbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps', 'Traps'], equipment: 'Barbell', instructions: 'Press barbell overhead from shoulder height. Stand or sit.' },
  { name: 'Seated Dumbbell Press', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: 'Dumbbells, Bench', instructions: 'Sit on bench, press dumbbells overhead.' },
  { name: 'Arnold Press', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: 'Dumbbells', instructions: 'Start palms facing you, rotate as you press overhead.' },
  { name: 'Lateral Raise', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Dumbbells', instructions: 'Raise dumbbells to sides until arms parallel to floor.' },
  { name: 'Cable Lateral Raise', category: 'Cable', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Raise cable handle to side, arm slightly bent.' },
  { name: 'Front Raise', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Dumbbells', instructions: 'Raise dumbbells in front to shoulder height.' },
  { name: 'Rear Delt Fly', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Traps'], equipment: 'Dumbbells', instructions: 'Bend at hips, raise dumbbells to sides targeting rear delts.' },
  { name: 'Face Pull', category: 'Cable', primaryMuscles: ['Shoulders', 'Traps'], secondaryMuscles: [], equipment: 'Cable Machine, Rope', instructions: 'Pull rope to face, externally rotate shoulders.' },
  { name: 'Upright Row', category: 'Barbell', primaryMuscles: ['Shoulders', 'Traps'], secondaryMuscles: [], equipment: 'Barbell', instructions: 'Pull barbell up along body to chin level.' },
  { name: 'Machine Shoulder Press', category: 'Machine', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: 'Shoulder Press Machine', instructions: 'Sit in machine, press handles overhead.' },
  { name: 'Reverse Pec Deck', category: 'Machine', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Traps'], equipment: 'Pec Deck Machine', instructions: 'Face the pad, pull handles back targeting rear delts.' },
  { name: 'Behind the Neck Press', category: 'Barbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: 'Barbell', instructions: 'Press barbell from behind neck overhead. Requires good mobility.' },
  { name: 'Push Press', category: 'Barbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps', 'Quads'], equipment: 'Barbell', instructions: 'Use leg drive to help press barbell overhead.' },
  { name: 'Bradford Press', category: 'Barbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], equipment: 'Barbell', instructions: 'Press over head alternating in front and behind.' },
  { name: 'Lu Raise', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Light Dumbbells', instructions: 'Raise dumbbells forward with thumbs pointing up at 45 degrees.' },
  { name: 'Y-Raise', category: 'Dumbbell', primaryMuscles: ['Shoulders', 'Traps'], secondaryMuscles: [], equipment: 'Light Dumbbells', instructions: 'Raise arms in Y-shape while bent over or on incline bench.' },

  // ============ BICEPS ============
  { name: 'Barbell Curl', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: 'Barbell', instructions: 'Standing, curl barbell from thighs to shoulders.' },
  { name: 'EZ Bar Curl', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: 'EZ Bar', instructions: 'Curl EZ bar with angled grip for comfort.' },
  { name: 'Dumbbell Curl', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: 'Dumbbells', instructions: 'Curl dumbbells alternately or simultaneously.' },
  { name: 'Hammer Curl', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: 'Dumbbells', instructions: 'Curl with neutral grip (thumbs up).' },
  { name: 'Incline Dumbbell Curl', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Dumbbells, Incline Bench', instructions: 'Lie back on incline bench, curl dumbbells for a stretch.' },
  { name: 'Preacher Curl', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'EZ Bar, Preacher Bench', instructions: 'Curl on preacher bench to isolate biceps.' },
  { name: 'Cable Curl', category: 'Cable', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: 'Cable Machine', instructions: 'Curl cable from low position.' },
  { name: 'Concentration Curl', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Dumbbell', instructions: 'Sit, brace elbow on inner thigh, curl dumbbell.' },
  { name: 'Spider Curl', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Dumbbells, Incline Bench', instructions: 'Lie face down on incline bench, curl dumbbells.' },
  { name: 'Machine Bicep Curl', category: 'Machine', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Bicep Curl Machine', instructions: 'Sit in machine, curl handles to shoulders.' },
  { name: 'Bayesian Cable Curl', category: 'Cable', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Stand facing away from cable, curl from behind.' },
  { name: 'Drag Curl', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Barbell', instructions: 'Curl barbell by dragging it up along the body.' },
  { name: 'Cross Body Curl', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'], equipment: 'Dumbbell', instructions: 'Curl dumbbell across the body to the opposite shoulder.' },

  // ============ TRICEPS ============
  { name: 'Tricep Pushdown', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Push cable down from chest to full extension.' },
  { name: 'Rope Pushdown', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'Cable Machine, Rope', instructions: 'Push rope down and spread at bottom.' },
  { name: 'Overhead Tricep Extension', category: 'Dumbbell', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'Dumbbell', instructions: 'Hold dumbbell overhead, lower behind head, extend.' },
  { name: 'Skull Crusher', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'EZ Bar, Bench', instructions: 'Lie on bench, lower bar to forehead, extend.' },
  { name: 'Cable Overhead Extension', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'Cable Machine, Rope', instructions: 'Face away from cable, extend rope overhead.' },
  { name: 'Dip (Tricep)', category: 'Bodyweight', primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest', 'Shoulders'], equipment: 'Dip Bars', instructions: 'Keep body upright on dip bars, lower and press.' },
  { name: 'Kickback', category: 'Dumbbell', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'Dumbbell', instructions: 'Bend over, extend dumbbell back to full extension.' },
  { name: 'JM Press', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest'], equipment: 'Barbell, Bench', instructions: 'Hybrid between close grip bench and skull crusher.' },
  { name: 'Bench Dip', category: 'Bodyweight', primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest'], equipment: 'Bench', instructions: 'Hands on bench behind you, lower body by bending arms.' },
  { name: 'Machine Tricep Extension', category: 'Machine', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'Tricep Machine', instructions: 'Sit in machine, push handles down to extend arms.' },

  // ============ QUADS ============
  { name: 'Barbell Squat', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Abs'], equipment: 'Barbell, Squat Rack', instructions: 'Bar on upper back, squat down until thighs parallel or below.' },
  { name: 'Front Squat', category: 'Barbell', primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes', 'Abs'], equipment: 'Barbell, Squat Rack', instructions: 'Bar on front delts, squat with upright torso.' },
  { name: 'Leg Press', category: 'Machine', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Leg Press Machine', instructions: 'Place feet on platform, press weight by extending legs.' },
  { name: 'Hack Squat', category: 'Machine', primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], equipment: 'Hack Squat Machine', instructions: 'Squat in hack squat machine for quad emphasis.' },
  { name: 'Leg Extension', category: 'Machine', primaryMuscles: ['Quads'], secondaryMuscles: [], equipment: 'Leg Extension Machine', instructions: 'Sit in machine, extend legs to straight position.' },
  { name: 'Goblet Squat', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: [], equipment: 'Dumbbell or Kettlebell', instructions: 'Hold weight at chest, squat down.' },
  { name: 'Bulgarian Split Squat', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Dumbbells, Bench', instructions: 'Rear foot elevated on bench, squat with front leg.' },
  { name: 'Walking Lunge', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Dumbbells', instructions: 'Step forward into lunge, alternate legs while walking.' },
  { name: 'Step Up', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: [], equipment: 'Dumbbells, Box', instructions: 'Step up onto box, one leg at a time.' },
  { name: 'Sissy Squat', category: 'Bodyweight', primaryMuscles: ['Quads'], secondaryMuscles: [], equipment: 'None', instructions: 'Lean back while squatting on toes to isolate quads.' },
  { name: 'Pause Squat', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Barbell, Squat Rack', instructions: 'Squat with 2-3 second pause at the bottom.' },
  { name: 'Box Squat', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Barbell, Box', instructions: 'Squat to a box, pause briefly, stand.' },
  { name: 'Safety Bar Squat', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Abs'], equipment: 'Safety Squat Bar', instructions: 'Squat using safety squat bar.' },
  { name: 'Belt Squat', category: 'Machine', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: [], equipment: 'Belt Squat Machine', instructions: 'Weight suspended from belt, squat without spinal loading.' },
  { name: 'Pistol Squat', category: 'Bodyweight', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'None', instructions: 'Single leg squat with other leg extended forward.' },
  { name: 'Smith Machine Squat', category: 'Machine', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Smith Machine', instructions: 'Squat using Smith machine for stability.' },
  { name: 'Reverse Lunge', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Dumbbells', instructions: 'Step backward into lunge position.' },

  // ============ HAMSTRINGS ============
  { name: 'Romanian Deadlift', category: 'Barbell', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: ['Back'], equipment: 'Barbell', instructions: 'Hinge at hips, lower bar along legs with slight knee bend.' },
  { name: 'Stiff Leg Deadlift', category: 'Barbell', primaryMuscles: ['Hamstrings'], secondaryMuscles: ['Glutes', 'Back'], equipment: 'Barbell', instructions: 'Deadlift with minimal knee bend for hamstring stretch.' },
  { name: 'Lying Leg Curl', category: 'Machine', primaryMuscles: ['Hamstrings'], secondaryMuscles: [], equipment: 'Leg Curl Machine', instructions: 'Lie face down, curl weight by bending knees.' },
  { name: 'Seated Leg Curl', category: 'Machine', primaryMuscles: ['Hamstrings'], secondaryMuscles: [], equipment: 'Seated Leg Curl Machine', instructions: 'Sit in machine, curl pad under thighs.' },
  { name: 'Dumbbell Romanian Deadlift', category: 'Dumbbell', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: ['Back'], equipment: 'Dumbbells', instructions: 'Hold dumbbells, hinge at hips.' },
  { name: 'Nordic Hamstring Curl', category: 'Bodyweight', primaryMuscles: ['Hamstrings'], secondaryMuscles: [], equipment: 'None, Partner or Anchor', instructions: 'Kneel, lower body eccentrically using hamstrings.' },
  { name: 'Good Morning', category: 'Barbell', primaryMuscles: ['Hamstrings', 'Back'], secondaryMuscles: ['Glutes'], equipment: 'Barbell', instructions: 'Bar on back, hinge forward at hips, return upright.' },
  { name: 'Single Leg Romanian Deadlift', category: 'Dumbbell', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: [], equipment: 'Dumbbell', instructions: 'Stand on one leg, hinge forward, extend other leg back.' },
  { name: 'Glute Ham Raise', category: 'Machine', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: [], equipment: 'GHD Machine', instructions: 'Use GHD machine to curl body up from hip hinge.' },

  // ============ GLUTES ============
  { name: 'Hip Thrust', category: 'Barbell', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Barbell, Bench', instructions: 'Back on bench, thrust hips up with bar on hips.' },
  { name: 'Glute Bridge', category: 'Bodyweight', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'None', instructions: 'Lie on back, thrust hips up squeezing glutes.' },
  { name: 'Cable Pull Through', category: 'Cable', primaryMuscles: ['Glutes', 'Hamstrings'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Face away from low cable, hinge and pull through.' },
  { name: 'Sumo Deadlift', category: 'Barbell', primaryMuscles: ['Glutes', 'Quads'], secondaryMuscles: ['Hamstrings', 'Back'], equipment: 'Barbell', instructions: 'Wide stance deadlift emphasizing glutes and inner thighs.' },
  { name: 'Kickback (Cable)', category: 'Cable', primaryMuscles: ['Glutes'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Kick leg back against cable resistance.' },
  { name: 'Hip Abduction Machine', category: 'Machine', primaryMuscles: ['Glutes'], secondaryMuscles: [], equipment: 'Hip Abduction Machine', instructions: 'Push pads outward to target outer glutes.' },
  { name: 'Frog Pump', category: 'Bodyweight', primaryMuscles: ['Glutes'], secondaryMuscles: [], equipment: 'None', instructions: 'Soles together, knees out, thrust hips up.' },
  { name: 'Single Leg Hip Thrust', category: 'Bodyweight', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'Bench', instructions: 'Perform hip thrust with one leg extended.' },

  // ============ CALVES ============
  { name: 'Standing Calf Raise', category: 'Machine', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'Calf Raise Machine', instructions: 'Rise up on toes, lower slowly.' },
  { name: 'Seated Calf Raise', category: 'Machine', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'Seated Calf Raise Machine', instructions: 'Sit with pad on knees, raise heels.' },
  { name: 'Leg Press Calf Raise', category: 'Machine', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'Leg Press Machine', instructions: 'Place toes on bottom of platform, press through toes.' },
  { name: 'Donkey Calf Raise', category: 'Machine', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'Donkey Calf Machine', instructions: 'Bend at hips, raise heels against resistance.' },
  { name: 'Single Leg Calf Raise', category: 'Bodyweight', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'Step', instructions: 'Stand on one foot on a step, raise and lower heel.' },

  // ============ ABS ============
  { name: 'Crunch', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'Lie on back, curl upper body toward knees.' },
  { name: 'Bicycle Crunch', category: 'Bodyweight', primaryMuscles: ['Abs', 'Obliques'], secondaryMuscles: [], equipment: 'None', instructions: 'Alternate bringing elbow to opposite knee in cycling motion.' },
  { name: 'Hanging Leg Raise', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: ['Obliques'], equipment: 'Pull-Up Bar', instructions: 'Hang from bar, raise legs to parallel or higher.' },
  { name: 'Hanging Knee Raise', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'Pull-Up Bar', instructions: 'Hang from bar, bring knees to chest.' },
  { name: 'Ab Wheel Rollout', category: 'Other', primaryMuscles: ['Abs'], secondaryMuscles: ['Shoulders'], equipment: 'Ab Wheel', instructions: 'Kneel, roll wheel forward and back with control.' },
  { name: 'Cable Crunch', category: 'Cable', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Kneel at cable, crunch down against resistance.' },
  { name: 'Plank', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: ['Shoulders'], equipment: 'None', instructions: 'Hold body in straight line on forearms and toes.' },
  { name: 'Side Plank', category: 'Bodyweight', primaryMuscles: ['Obliques', 'Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'Hold body on one forearm, sideways.' },
  { name: 'Russian Twist', category: 'Bodyweight', primaryMuscles: ['Obliques', 'Abs'], secondaryMuscles: [], equipment: 'None or Weight', instructions: 'Sit leaning back, rotate torso side to side.' },
  { name: 'Decline Sit-Up', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'Decline Bench', instructions: 'Sit-up on decline bench for increased difficulty.' },
  { name: 'Leg Raise', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'Lie on back, raise legs to vertical.' },
  { name: 'Mountain Climber', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: ['Shoulders'], equipment: 'None', instructions: 'In push-up position, alternate bringing knees to chest quickly.' },
  { name: 'Pallof Press', category: 'Cable', primaryMuscles: ['Abs', 'Obliques'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Stand sideways to cable, press handles forward resisting rotation.' },
  { name: 'Dead Bug', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'Lie on back, extend opposite arm and leg while keeping core braced.' },
  { name: 'Woodchopper', category: 'Cable', primaryMuscles: ['Obliques', 'Abs'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Rotate torso diagonally against cable resistance.' },
  { name: 'Dragon Flag', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'Bench', instructions: 'Lie on bench, raise entire body in straight line on shoulders.' },
  { name: 'V-Up', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'Lie flat, simultaneously raise legs and upper body to touch toes.' },
  { name: 'Toe Touch', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'Lie on back with legs vertical, reach up to touch toes.' },

  // ============ TRAPS ============
  { name: 'Barbell Shrug', category: 'Barbell', primaryMuscles: ['Traps'], secondaryMuscles: [], equipment: 'Barbell', instructions: 'Hold barbell at thigh level, shrug shoulders up.' },
  { name: 'Dumbbell Shrug', category: 'Dumbbell', primaryMuscles: ['Traps'], secondaryMuscles: [], equipment: 'Dumbbells', instructions: 'Hold dumbbells at sides, shrug shoulders up.' },
  { name: 'Trap Bar Shrug', category: 'Barbell', primaryMuscles: ['Traps'], secondaryMuscles: [], equipment: 'Trap Bar', instructions: 'Stand in trap bar, shrug shoulders.' },
  { name: 'Cable Shrug', category: 'Cable', primaryMuscles: ['Traps'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Shrug against cable resistance.' },
  { name: 'Farmer Walk', category: 'Other', primaryMuscles: ['Traps', 'Forearms'], secondaryMuscles: ['Abs'], equipment: 'Heavy Dumbbells or Farmer Handles', instructions: 'Carry heavy weights and walk.' },
  { name: 'Rack Pull', category: 'Barbell', primaryMuscles: ['Traps', 'Back'], secondaryMuscles: ['Glutes'], equipment: 'Barbell, Power Rack', instructions: 'Deadlift from pins at knee height.' },

  // ============ FOREARMS ============
  { name: 'Wrist Curl', category: 'Barbell', primaryMuscles: ['Forearms'], secondaryMuscles: [], equipment: 'Barbell or Dumbbell', instructions: 'Forearms on bench, curl wrists up.' },
  { name: 'Reverse Wrist Curl', category: 'Barbell', primaryMuscles: ['Forearms'], secondaryMuscles: [], equipment: 'Barbell or Dumbbell', instructions: 'Forearms on bench palms down, extend wrists up.' },
  { name: 'Reverse Curl', category: 'Barbell', primaryMuscles: ['Forearms', 'Biceps'], secondaryMuscles: [], equipment: 'Barbell or EZ Bar', instructions: 'Curl with overhand grip.' },
  { name: 'Plate Pinch', category: 'Other', primaryMuscles: ['Forearms'], secondaryMuscles: [], equipment: 'Weight Plates', instructions: 'Pinch plates together and hold.' },
  { name: 'Dead Hang', category: 'Bodyweight', primaryMuscles: ['Forearms'], secondaryMuscles: ['Back'], equipment: 'Pull-Up Bar', instructions: 'Hang from bar for time to build grip.' },

  // ============ DEADLIFT VARIATIONS ============
  { name: 'Deadlift', category: 'Barbell', primaryMuscles: ['Back', 'Hamstrings', 'Glutes'], secondaryMuscles: ['Quads', 'Traps', 'Forearms'], equipment: 'Barbell', instructions: 'Stand over bar, grip and lift by extending hips and knees.' },
  { name: 'Deficit Deadlift', category: 'Barbell', primaryMuscles: ['Back', 'Hamstrings', 'Glutes'], secondaryMuscles: ['Quads'], equipment: 'Barbell, Platform', instructions: 'Stand on slight elevation, deadlift with increased ROM.' },
  { name: 'Pause Deadlift', category: 'Barbell', primaryMuscles: ['Back', 'Hamstrings', 'Glutes'], secondaryMuscles: ['Quads'], equipment: 'Barbell', instructions: 'Deadlift with 2-3 second pause below knees.' },
  { name: 'Trap Bar Deadlift', category: 'Barbell', primaryMuscles: ['Quads', 'Back', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Traps'], equipment: 'Trap Bar', instructions: 'Stand in trap bar, lift by extending hips and knees.' },
  { name: 'Snatch Grip Deadlift', category: 'Barbell', primaryMuscles: ['Back', 'Hamstrings', 'Glutes', 'Traps'], secondaryMuscles: ['Quads'], equipment: 'Barbell', instructions: 'Very wide grip deadlift for upper back emphasis.' },
  { name: 'Block Pull', category: 'Barbell', primaryMuscles: ['Back', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Traps'], equipment: 'Barbell, Blocks', instructions: 'Deadlift from elevated blocks.' },

  // ============ OLYMPIC / POWER ============
  { name: 'Power Clean', category: 'Barbell', primaryMuscles: ['Full Body'], secondaryMuscles: ['Quads', 'Back', 'Shoulders', 'Traps'], equipment: 'Barbell', instructions: 'Explosively clean barbell from floor to shoulders.' },
  { name: 'Hang Clean', category: 'Barbell', primaryMuscles: ['Full Body'], secondaryMuscles: ['Quads', 'Back', 'Traps'], equipment: 'Barbell', instructions: 'Clean barbell from hang position to shoulders.' },
  { name: 'Snatch', category: 'Barbell', primaryMuscles: ['Full Body'], secondaryMuscles: ['Shoulders', 'Back', 'Quads'], equipment: 'Barbell', instructions: 'Lift barbell from floor to overhead in one motion.' },
  { name: 'Clean and Jerk', category: 'Barbell', primaryMuscles: ['Full Body'], secondaryMuscles: ['Shoulders', 'Quads', 'Back'], equipment: 'Barbell', instructions: 'Clean to shoulders, then jerk overhead.' },
  { name: 'Thruster', category: 'Barbell', primaryMuscles: ['Quads', 'Shoulders'], secondaryMuscles: ['Glutes', 'Triceps'], equipment: 'Barbell', instructions: 'Front squat into overhead press in one fluid motion.' },
  { name: 'Kettlebell Swing', category: 'Other', primaryMuscles: ['Glutes', 'Hamstrings'], secondaryMuscles: ['Back', 'Shoulders', 'Abs'], equipment: 'Kettlebell', instructions: 'Hinge at hips, swing kettlebell to shoulder height.' },
  { name: 'Turkish Get-Up', category: 'Other', primaryMuscles: ['Full Body'], secondaryMuscles: ['Shoulders', 'Abs'], equipment: 'Kettlebell or Dumbbell', instructions: 'From lying to standing while holding weight overhead.' },

  // ============ NECK ============
  { name: 'Neck Curl', category: 'Other', primaryMuscles: ['Neck'], secondaryMuscles: [], equipment: 'Neck Harness or Plate', instructions: 'Curl neck forward against resistance.' },
  { name: 'Neck Extension', category: 'Other', primaryMuscles: ['Neck'], secondaryMuscles: [], equipment: 'Neck Harness or Plate', instructions: 'Extend neck backward against resistance.' },
  { name: 'Neck Lateral Flexion', category: 'Other', primaryMuscles: ['Neck'], secondaryMuscles: [], equipment: 'Band or Manual', instructions: 'Tilt head to side against resistance.' },

  // ============ CARDIO ============
  { name: 'Treadmill Running', category: 'Cardio', primaryMuscles: ['Full Body'], secondaryMuscles: ['Quads', 'Hamstrings', 'Calves'], equipment: 'Treadmill', instructions: 'Run on treadmill at chosen pace.' },
  { name: 'Treadmill Walking', category: 'Cardio', primaryMuscles: ['Full Body'], secondaryMuscles: [], equipment: 'Treadmill', instructions: 'Walk on treadmill, use incline for added difficulty.' },
  { name: 'Elliptical', category: 'Cardio', primaryMuscles: ['Full Body'], secondaryMuscles: [], equipment: 'Elliptical Machine', instructions: 'Use elliptical at chosen resistance and pace.' },
  { name: 'Stationary Bike', category: 'Cardio', primaryMuscles: ['Quads', 'Hamstrings'], secondaryMuscles: ['Calves'], equipment: 'Stationary Bike', instructions: 'Cycle at chosen resistance and cadence.' },
  { name: 'Rowing Machine', category: 'Cardio', primaryMuscles: ['Back', 'Full Body'], secondaryMuscles: ['Biceps', 'Quads'], equipment: 'Rowing Machine', instructions: 'Row at chosen resistance and pace.' },
  { name: 'Stair Climber', category: 'Cardio', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Calves'], equipment: 'Stair Climber', instructions: 'Climb stairs at chosen speed.' },
  { name: 'Jump Rope', category: 'Cardio', primaryMuscles: ['Calves', 'Full Body'], secondaryMuscles: ['Shoulders'], equipment: 'Jump Rope', instructions: 'Jump rope at chosen pace and style.' },
  { name: 'Battle Ropes', category: 'Cardio', primaryMuscles: ['Shoulders', 'Full Body'], secondaryMuscles: ['Arms', 'Abs'], equipment: 'Battle Ropes', instructions: 'Create waves with heavy ropes.' },
  { name: 'Burpees', category: 'Bodyweight', primaryMuscles: ['Full Body'], secondaryMuscles: [], equipment: 'None', instructions: 'Drop to push-up, jump up, repeat.' },
  { name: 'Box Jump', category: 'Bodyweight', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Calves'], equipment: 'Box', instructions: 'Jump onto box, step down, repeat.' },
  { name: 'Sled Push', category: 'Other', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Calves', 'Shoulders'], equipment: 'Sled', instructions: 'Push loaded sled across floor.' },
  { name: 'Sled Pull', category: 'Other', primaryMuscles: ['Back', 'Hamstrings'], secondaryMuscles: ['Biceps'], equipment: 'Sled, Rope', instructions: 'Pull sled toward you using rope.' },

  // ============ STRETCHING / MOBILITY ============
  { name: 'Foam Rolling', category: 'Stretching', primaryMuscles: ['Full Body'], secondaryMuscles: [], equipment: 'Foam Roller', instructions: 'Roll targeted muscles on foam roller.' },
  { name: 'Hamstring Stretch', category: 'Stretching', primaryMuscles: ['Hamstrings'], secondaryMuscles: [], equipment: 'None', instructions: 'Stretch hamstrings in various positions.' },
  { name: 'Quad Stretch', category: 'Stretching', primaryMuscles: ['Quads'], secondaryMuscles: [], equipment: 'None', instructions: 'Pull heel to glute to stretch quad.' },
  { name: 'Hip Flexor Stretch', category: 'Stretching', primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], equipment: 'None', instructions: 'Lunge position, push hips forward.' },
  { name: 'Shoulder Stretch', category: 'Stretching', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'None or Band', instructions: 'Various shoulder stretches and dislocates.' },
  { name: 'Chest Stretch', category: 'Stretching', primaryMuscles: ['Chest'], secondaryMuscles: [], equipment: 'Doorway or Wall', instructions: 'Stretch chest using doorway or wall.' },
  { name: 'Cat-Cow Stretch', category: 'Stretching', primaryMuscles: ['Back', 'Abs'], secondaryMuscles: [], equipment: 'None', instructions: 'On all fours, alternate arching and rounding back.' },
  { name: 'Pigeon Stretch', category: 'Stretching', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], equipment: 'None', instructions: 'One leg bent forward, other extended back for deep hip stretch.' },
  { name: 'World\'s Greatest Stretch', category: 'Stretching', primaryMuscles: ['Full Body'], secondaryMuscles: [], equipment: 'None', instructions: 'Dynamic stretch combining lunge, twist, and reach.' },
  { name: 'Band Pull Apart', category: 'Band', primaryMuscles: ['Shoulders', 'Traps'], secondaryMuscles: [], equipment: 'Resistance Band', instructions: 'Hold band at arms length, pull apart horizontally.' },
  { name: 'Band Dislocate', category: 'Band', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Resistance Band', instructions: 'Wide grip, pass band from front to behind back overhead.' },

  // ============ ADDITIONAL POPULAR EXERCISES ============
  { name: 'Dumbbell Pullover', category: 'Dumbbell', primaryMuscles: ['Chest', 'Lats'], secondaryMuscles: ['Triceps'], equipment: 'Dumbbell, Bench', instructions: 'Lie across bench, lower dumbbell behind head, pull over.' },
  { name: 'Machine Fly', category: 'Machine', primaryMuscles: ['Chest'], secondaryMuscles: [], equipment: 'Fly Machine', instructions: 'Bring handles together in front of chest.' },
  { name: 'Cable Bicep Curl', category: 'Cable', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Curl cable handles up from low position.' },
  { name: 'Machine Lat Pulldown', category: 'Machine', primaryMuscles: ['Lats', 'Back'], secondaryMuscles: ['Biceps'], equipment: 'Lat Pulldown Machine', instructions: 'Pull bar down to upper chest.' },
  { name: 'Leg Curl', category: 'Machine', primaryMuscles: ['Hamstrings'], secondaryMuscles: [], equipment: 'Leg Curl Machine', instructions: 'Curl weight by bending knees.' },
  { name: 'Calf Raise', category: 'Bodyweight', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'None', instructions: 'Rise up on toes, lower slowly.' },
  { name: 'Ab Crunch Machine', category: 'Machine', primaryMuscles: ['Abs'], secondaryMuscles: [], equipment: 'Ab Crunch Machine', instructions: 'Sit in machine, crunch forward against resistance.' },
  { name: 'Hyperextension', category: 'Bodyweight', primaryMuscles: ['Back', 'Hamstrings'], secondaryMuscles: ['Glutes'], equipment: 'Hyperextension Bench', instructions: 'Hinge at hips on hyperextension bench, raise torso.' },
  { name: 'Lat Raise Machine', category: 'Machine', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Lateral Raise Machine', instructions: 'Raise arms against pads to side.' },
  { name: 'Cable Fly', category: 'Cable', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: 'Cable Machine', instructions: 'Bring cable handles together in arc motion at chest height.' },
  { name: 'Incline Cable Fly', category: 'Cable', primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], equipment: 'Cable Machine, Incline Bench', instructions: 'Fly motion on incline targeting upper chest.' },
  { name: 'Chest Dip', category: 'Bodyweight', primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], equipment: 'Dip Bars', instructions: 'Lean forward on bars, lower and push.' },
  { name: 'Wide Grip Pull-Up', category: 'Bodyweight', primaryMuscles: ['Lats', 'Back'], secondaryMuscles: ['Biceps'], equipment: 'Pull-Up Bar', instructions: 'Pull up with wide grip for lat emphasis.' },
  { name: 'Neutral Grip Pull-Up', category: 'Bodyweight', primaryMuscles: ['Back', 'Lats'], secondaryMuscles: ['Biceps'], equipment: 'Pull-Up Bar with Neutral Grips', instructions: 'Pull up with palms facing each other.' },
  { name: 'High Cable Curl', category: 'Cable', primaryMuscles: ['Biceps'], secondaryMuscles: [], equipment: 'Cable Machine', instructions: 'Curl from overhead cable position.' },
  { name: 'Lying Tricep Extension', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: [], equipment: 'EZ Bar, Bench', instructions: 'Lie on bench, lower bar behind head, extend.' },
  { name: 'Single Arm Dumbbell Press', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps', 'Abs'], equipment: 'Dumbbell', instructions: 'Press one dumbbell overhead for core engagement.' },
  { name: 'Hip Adduction Machine', category: 'Machine', primaryMuscles: ['Glutes'], secondaryMuscles: [], equipment: 'Hip Adduction Machine', instructions: 'Squeeze pads inward with inner thighs.' },
  { name: 'Leg Press Calf Raise', category: 'Machine', primaryMuscles: ['Calves'], secondaryMuscles: [], equipment: 'Leg Press', instructions: 'Ball of feet on platform edge, press through toes.' },
  { name: 'Zercher Squat', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Abs', 'Biceps'], equipment: 'Barbell', instructions: 'Hold barbell in crooks of elbows, squat.' },
  { name: 'Dumbbell Lateral Raise', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Dumbbells', instructions: 'Raise dumbbells to sides.' },
  { name: 'Dumbbell Front Raise', category: 'Dumbbell', primaryMuscles: ['Shoulders'], secondaryMuscles: [], equipment: 'Dumbbells', instructions: 'Raise dumbbells to front.' },
  { name: 'Close Grip Lat Pulldown', category: 'Cable', primaryMuscles: ['Lats', 'Back'], secondaryMuscles: ['Biceps'], equipment: 'Lat Pulldown Machine', instructions: 'Pull with close/neutral grip for lower lat emphasis.' },
];

// Mark all as default non-custom exercises
const exerciseData = exercises.map(e => ({
  ...e,
  isCustom: false,
  isDefault: true,
}));

module.exports = exerciseData;
